module.exports = {
	coupon_code: { type: String },
	status: { type: String, default: "Unused" },
	referrer: { type: String },
	referrer_id: { type: String },
	consumer: { type: String },
	expiry_date: { type: Date },
	brand_id: { type: String },
	total_purchase_amount: { type: Number },
	discounted_amount: { type: Number },
	total_paid_amount: { type: Number },
	referral_amount: { type: Number },
	bub_amount: { type: Number },
	vendor_payment_status: { type: String },
	vendor_transaction_id: { type: String },
	referral_payment_status: { type: String },
	invoice_created_at: { type: Date },
	created_at: { type: Date, default: Date.now },
	updated_at: { type: Date, default: Date.now }
}